version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: gradle
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
