import { useCallback, useEffect, useState, type FormEvent } from "react";
import { BarChart3, Boxes, ClipboardCheck, PackagePlus, Truck } from "lucide-react";
import { api, type AdminReturnRow, type AdminStats, type CategoryRow, type CustomerRow, type InventoryRow, type ModerationRow, type SupplierRow } from "../../lib/api";
import { useStore } from "../../context/StoreContext";
import type { Order } from "../../types/store";

export function OperationsPage() {
  const { token, user, catalog, refreshProducts } = useStore();
  const [stats, setStats] = useState<AdminStats | null>(null); const [orders, setOrders] = useState<Order[]>([]);
  const [categories, setCategories] = useState<CategoryRow[]>([]); const [suppliers, setSuppliers] = useState<SupplierRow[]>([]);
  const [movements, setMovements] = useState<InventoryRow[]>([]); const [moderation, setModeration] = useState<ModerationRow[]>([]);
  const [returns, setReturns] = useState<AdminReturnRow[]>([]);
  const [customers, setCustomers] = useState<CustomerRow[]>([]);
  const [message, setMessage] = useState("");
  const [categoryName, setCategoryName] = useState("");
  const [supplier, setSupplier] = useState({ name: "", taxId: "", email: "", phone: "" });
  const [movement, setMovement] = useState({ productId: "", type: "ENTRY", quantity: 1, reference: "" });
  const isAdmin = user?.roles.includes("ADMIN");

  const load = useCallback(async () => {
    if (!token || !isAdmin) return;
    try {
      const [s, o, c, p, i, m, r, u] = await Promise.all([api.adminStats(token), api.adminOrders(token), api.adminCategories(token), api.suppliers(token), api.inventory(token), api.moderation(token), api.adminReturns(token), api.customers(token)]);
      setStats(s); setOrders(o.orders); setCategories(c.categories); setSuppliers(p.suppliers); setMovements(i.movements); setModeration(m.products); setReturns(r.returns); setCustomers(u.customers);
    } catch (e) { setMessage(e instanceof Error ? e.message : "No se pudieron cargar las operaciones"); }
  }, [token, isAdmin]);
  useEffect(() => { void load(); }, [load]);

  async function createCategory(e: FormEvent) { e.preventDefault(); if (!token) return; await api.createCategory(token, { name: categoryName }); setCategoryName(""); await load(); }
  async function createSupplier(e: FormEvent) { e.preventDefault(); if (!token) return; await api.createSupplier(token, { ...supplier, status: "ACTIVE", productIds: [] }); setSupplier({ name: "", taxId: "", email: "", phone: "" }); await load(); }
  async function createMovement(e: FormEvent) { e.preventDefault(); if (!token) return; await api.inventoryMovement(token, movement); setMovement({ productId: "", type: "ENTRY", quantity: 1, reference: "" }); await refreshProducts(); await load(); }
  async function changeOrder(id: string, status: string) { if (!token) return; await api.adminOrderPatch(token, id, status); await load(); }
  async function moderate(productId: string, decision: string) { if (!token) return; const note = decision === "APPROVED" ? undefined : window.prompt("Motivo obligatorio") ?? undefined; if (decision !== "APPROVED" && !note) return; await api.moderate(token, productId, decision, note); await refreshProducts(); await load(); }
  async function changeReturn(id: string, status: string) { if (!token) return; const note = window.prompt("Nota administrativa") ?? undefined; await api.adminReturnPatch(token, id, { status, adminNote: note }); await load(); }
  async function toggleCustomer(id: number, enabled: boolean) { if (!token) return; await api.customerStatus(token, id, enabled); await load(); }

  if (!isAdmin) return <section className="mx-auto max-w-xl py-20 text-center"><h1 className="text-3xl font-black">Acceso administrativo requerido</h1></section>;
  return <div className="space-y-7">
    <header className="rounded-[2rem] bg-[#0a0f1a] p-8 text-white"><p className="text-sm font-bold uppercase tracking-[.2em] text-primary">Operación persistente</p><h1 className="mt-2 text-4xl font-black">Inventario, pedidos y control</h1><p className="mt-2 text-white/65">Todos los indicadores provienen del backend y PostgreSQL.</p></header>
    {message && <p className="rounded-xl bg-amber-50 p-4 text-amber-900">{message}</p>}
    {stats && <section className="grid gap-4 md:grid-cols-5">{[["Pedidos",stats.summary.ordersCount],["Ingresos",`USD ${stats.summary.revenueUsd}`],["Unidades",stats.summary.unitsSold],["Devoluciones",stats.summary.returnsPending],["Stock bajo",stats.summary.lowStockProducts]].map(([label,value])=><article key={String(label)} className="rounded-2xl border bg-white p-5"><BarChart3 className="text-accent"/><p className="mt-3 text-xs font-bold uppercase text-neutral-400">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></article>)}</section>}
    <section className="grid gap-6 xl:grid-cols-3">
      <form onSubmit={createCategory} className="rounded-[2rem] border bg-white p-6"><ClipboardCheck/><h2 className="mt-3 text-xl font-black">Nueva categoría</h2><input required value={categoryName} onChange={e=>setCategoryName(e.target.value)} placeholder="Nombre" className="mt-4 w-full rounded-xl border px-4 py-3"/><button className="mt-3 w-full rounded-xl bg-neutral-950 px-4 py-3 font-bold text-white">Guardar</button><p className="mt-3 text-xs text-neutral-500">{categories.length} categorías registradas</p></form>
      <form onSubmit={createSupplier} className="rounded-[2rem] border bg-white p-6"><Truck/><h2 className="mt-3 text-xl font-black">Nuevo proveedor</h2>{([['name','Nombre'],['taxId','RUC/identificación'],['email','Correo'],['phone','Teléfono']] as const).map(([key,label])=><input key={key} required={key==='name'||key==='taxId'} value={supplier[key]} onChange={e=>setSupplier({...supplier,[key]:e.target.value})} placeholder={label} className="mt-3 w-full rounded-xl border px-4 py-3"/>)}<button className="mt-3 w-full rounded-xl bg-neutral-950 px-4 py-3 font-bold text-white">Guardar</button><p className="mt-3 text-xs text-neutral-500">{suppliers.length} proveedores</p></form>
      <form onSubmit={createMovement} className="rounded-[2rem] border bg-white p-6"><PackagePlus/><h2 className="mt-3 text-xl font-black">Movimiento de inventario</h2><select required value={movement.productId} onChange={e=>setMovement({...movement,productId:e.target.value})} className="mt-4 w-full rounded-xl border px-4 py-3"><option value="">Producto</option>{catalog.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="mt-3 grid grid-cols-2 gap-3"><select value={movement.type} onChange={e=>setMovement({...movement,type:e.target.value})} className="rounded-xl border px-4 py-3"><option>ENTRY</option><option>EXIT</option><option>ADJUSTMENT</option></select><input type="number" min={1} value={movement.quantity} onChange={e=>setMovement({...movement,quantity:Number(e.target.value)})} className="rounded-xl border px-4 py-3"/></div><input value={movement.reference} onChange={e=>setMovement({...movement,reference:e.target.value})} placeholder="Referencia" className="mt-3 w-full rounded-xl border px-4 py-3"/><button className="mt-3 w-full rounded-xl bg-neutral-950 px-4 py-3 font-bold text-white">Registrar</button></form>
    </section>
    <section className="rounded-[2rem] border bg-white p-6"><div className="flex items-center gap-3"><Boxes/><h2 className="text-2xl font-black">Pedidos y seguimiento</h2></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead><tr className="border-b text-left"><th className="p-3">Pedido</th><th>Fecha</th><th>Total</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-b"><td className="p-3 font-mono">{o.id.slice(0,8)}</td><td>{new Date(o.createdAt).toLocaleString()}</td><td>USD {o.totalUsd}</td><td>{o.status}</td><td className="space-x-2">{({PENDING_WHATSAPP:['CONFIRMED','CANCELLED'],CONFIRMED:['PREPARING','CANCELLED'],PREPARING:['SHIPPED','CANCELLED'],SHIPPED:['DELIVERED']} as Record<string,string[]>)[o.status]?.map(s=><button key={s} onClick={()=>void changeOrder(o.id,s)} className="rounded-lg border px-2 py-1">{s}</button>)}</td></tr>)}</tbody></table></div></section>
    <section className="rounded-[2rem] border bg-white p-6"><h2 className="text-2xl font-black">Devoluciones</h2><div className="mt-4 space-y-3">{returns.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-neutral-50 p-4"><div><b>{r.userEmail}</b><p className="text-sm text-neutral-500">{r.quantity} × {r.productId} · {r.reason}</p></div><div className="space-x-2"><span className="text-sm font-bold">{r.status}</span>{r.status==='REQUESTED'&&<><button onClick={()=>void changeReturn(r.id,'APPROVED')} className="rounded-lg bg-emerald-600 px-3 py-1 text-white">Aprobar</button><button onClick={()=>void changeReturn(r.id,'REJECTED')} className="rounded-lg bg-red-600 px-3 py-1 text-white">Rechazar</button></>}{r.status==='APPROVED'&&<button onClick={()=>void changeReturn(r.id,'RECEIVED')} className="rounded-lg bg-accent px-3 py-1 text-white">Recibida</button>}</div></div>)}</div></section>
    <section className="rounded-[2rem] border bg-white p-6"><h2 className="text-2xl font-black">Clientes</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{customers.map(c=><div key={c.id} className="flex items-center justify-between rounded-xl bg-neutral-50 p-4"><div><b>{c.firstName} {c.lastName}</b><p className="text-sm text-neutral-500">{c.email}</p></div><button onClick={()=>void toggleCustomer(c.id,!c.enabled)} className={`rounded-lg px-3 py-1 text-sm font-bold ${c.enabled?'bg-emerald-100 text-emerald-800':'bg-red-100 text-red-800'}`}>{c.enabled?'Activo':'Deshabilitado'}</button></div>)}</div></section>
    <section className="grid gap-6 lg:grid-cols-2"><article className="rounded-[2rem] border bg-white p-6"><h2 className="text-2xl font-black">Cola de moderación</h2><div className="mt-4 space-y-3">{moderation.map(p=><div key={p.productId} className="rounded-xl bg-neutral-50 p-4"><b>{p.name}</b><p className="text-sm text-neutral-500">{p.status}</p><div className="mt-2 space-x-2"><button onClick={()=>void moderate(p.productId,'APPROVED')} className="rounded-lg bg-emerald-600 px-3 py-1 text-white">Aprobar</button><button onClick={()=>void moderate(p.productId,'OBSERVED')} className="rounded-lg bg-amber-500 px-3 py-1">Observar</button><button onClick={()=>void moderate(p.productId,'REJECTED')} className="rounded-lg bg-red-600 px-3 py-1 text-white">Rechazar</button></div></div>)}</div></article><article className="rounded-[2rem] border bg-white p-6"><h2 className="text-2xl font-black">Últimos movimientos</h2><ul className="mt-4 space-y-3">{movements.slice(0,10).map(m=><li key={m.id} className="flex justify-between rounded-xl bg-neutral-50 p-3 text-sm"><span>{m.type} · {m.productName}</span><b>{m.quantity} → {m.resultingStock}</b></li>)}</ul></article></section>
  </div>;
}
